name: tt Run and Publish

# Controls when the workflow will run
on:
  push:
    branches: [main]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch: 
    inputs:
      glossaryDefFile:
        required: true
        default: glossary.json
        description: glossaryDefFile
      deployBranch:
        required: false
        default: gh_pages
        description: This is where the output of script will be pushed to.


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2.2.2
      
      - name: Install deps
        run: |
          git clone https://github.com/trustoverip/tt.git
          python -m pip install marko
        
      - name: Set variables
        env:
          DEFAULT_GLOSSARY_DEF_FILE: glossary.json
          DEFAULT_DEPLOY_BRANCH: gh_pages
        run: |
          echo "GLOSSARY_DEF_FILE=${{ github.event.inputs.glossaryDefFile || env.DEFAULT_GLOSSARY_DEF_FILE }}" >> $GITHUB_ENV
          echo "DEPLOY_BRANCH=${{ github.event.inputs.deployBranch || env.DEFAULT_DEPLOY_BRANCH }}" >> $GITHUB_ENV

      - name: Run script
        run: ./tt/bin/tt glossary ${{ env.GLOSSARY_DEF_FILE }} >glossary.html
        
      - name: Publishing
        run: |
          mkdir public
          cp glossary.html public
          cd public
          git config --global init.defaultBranch main
          git init
          git config --local user.email "${{ github.actor }}@users.noreply.github.com"
          git config --local user.name "${{ github.actor }}"
          git add .
          git commit -m "Add changes" -a
          git push -f https://${{ secrets.ACCESS_TOKEN }}@github.com/${{ github.repository}}.git main:${{ env.DEPLOY_BRANCH }}
          echo DONE

